In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd
import numpy as np
# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load pandas

In [3]:
data = pd.read_json('/home/jia/Dropbox/Startup/code/Talentful/data/featureLinkGit.json')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 702065 entries, 0 to 99999
Data columns (total 28 columns):
bio_simi              702065 non-null float64
company_company       702065 non-null int64
count                 702065 non-null int64
edu_exp_simi          702065 non-null float64
exp_desc_simi         702065 non-null float64
gitlang_simi          702065 non-null float64
idGit                 702065 non-null int64
idLink                702065 non-null object
label                 702065 non-null int64
linkedin_gitblog      702065 non-null float64
linkedin_gitweb       702065 non-null float64
linkweb_gitblog       702065 non-null float64
linkweb_github        702065 non-null float64
linkweb_gitweb        702065 non-null float64
location_fuzz_sort    702065 non-null int64
login_fuzz            702065 non-null int64
login_jw              702065 non-null float64
name_dmetaphone       702065 non-null float64
name_fuzz             702065 non-null int64
name_jw               702065 non-null float64
name_leven            702065 non-null int64
org_company           702065 non-null int64
org_school            702065 non-null int64
pro_pub_desc_simi     702065 non-null float64
pro_pub_title_simi    702065 non-null float64
school_company        702065 non-null int64
skill_simi            702065 non-null float64
summary_simi          702065 non-null float64
dtypes: float64(16), int64(11), object(1)
memory usage: 155.3+ MB

In [5]:
data.head()

,bio_simi,company_company,count,edu_exp_simi,exp_desc_simi,gitlang_simi,idGit,idLink,label,linkedin_gitblog,...,name_fuzz,name_jw,name_leven,org_company,org_school,pro_pub_desc_simi,pro_pub_title_simi,school_company,skill_simi,summary_simi
0,-1.0,0,109,-1.0,0.0,0.092529,100138,g605854,0,0.670411,...,100,1.00000,0,0,0,-1.0,-1.0,0,0.017756,-1.000000
1,-1.0,0,109,-1.0,-1.0,0.000000,100138,g3326641,0,0.666667,...,71,0.90000,10,0,0,-1.0,-1.0,0,0.000000,-1.000000
10,0.0,31,109,0.0,-1.0,-1.000000,100138,g78494,0,0.800000,...,100,1.00000,0,0,0,-1.0,-1.0,37,-1.000000,0.157574
100,-1.0,0,109,-1.0,0.0,0.000000,100138,g3385103,0,0.670411,...,100,1.00000,0,0,0,-1.0,-1.0,0,0.000000,-1.000000
1000,-1.0,0,162,-1.0,-1.0,-1.000000,124676,g3246920,0,0.670411,...,62,0.84615,5,0,0,-1.0,-1.0,0,-1.000000,-1.000000

In [7]:
data['is_train'] = np.random.uniform(0, 1, len(data)) <= .75

In [8]:
data.head()

,bio_simi,company_company,count,edu_exp_simi,exp_desc_simi,gitlang_simi,idGit,idLink,label,linkedin_gitblog,...,name_jw,name_leven,org_company,org_school,pro_pub_desc_simi,pro_pub_title_simi,school_company,skill_simi,summary_simi,is_train
0,-1.0,0,109,-1.0,0.0,0.092529,100138,g605854,0,0.670411,...,1.00000,0,0,0,-1.0,-1.0,0,0.017756,-1.000000,True
1,-1.0,0,109,-1.0,-1.0,0.000000,100138,g3326641,0,0.666667,...,0.90000,10,0,0,-1.0,-1.0,0,0.000000,-1.000000,False
10,0.0,31,109,0.0,-1.0,-1.000000,100138,g78494,0,0.800000,...,1.00000,0,0,0,-1.0,-1.0,37,-1.000000,0.157574,True
100,-1.0,0,109,-1.0,0.0,0.000000,100138,g3385103,0,0.670411,...,1.00000,0,0,0,-1.0,-1.0,0,0.000000,-1.000000,True
1000,-1.0,0,162,-1.0,-1.0,-1.000000,124676,g3246920,0,0.670411,...,0.84615,5,0,0,-1.0,-1.0,0,-1.000000,-1.000000,True

In [9]:
train, test = data[data['is_train']==True], data[data['is_train']==False]

In [10]:
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

('Number of observations in the training data:', 526453)
('Number of observations in the test data:', 175612)

In [21]:
rfModel = RandomForestClassifier(n_estimators = 250 , max_depth = 20, random_state=0, verbose = 1)

In [22]:
y = pd.factorize(train['label'])[0]

In [70]:
features = ['bio_simi','edu_exp_simi','gitlang_simi','pro_pub_title_simi','pro_pub_desc_simi','skill_simi','summary_simi','exp_desc_simi','count','name_leven','name_dmetaphone','name_jw','name_fuzz','login_fuzz','login_jw','location_fuzz_sort','school_company','company_company','linkedin_gitblog','linkedin_gitweb','linkweb_gitblog','linkweb_gitweb','linkweb_github']

In [71]:
rfModel.fit(train[features],y)

[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:  6.5min finished

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=20, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=250, n_jobs=1,
            oob_score=False, random_state=0, verbose=1, warm_start=False)

In [72]:
rfModel.score(train[features],y)

[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:   56.8s finished

0.9834895042862326

In [37]:
y_test = pd.factorize(test['label'])[0]

In [53]:
y_score = loaded_model.predict(test[features])

[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:   18.6s finished

In [77]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175612 entries, 1 to 99998
Data columns (total 30 columns):
bio_simi              175612 non-null float64
company_company       175612 non-null int64
count                 175612 non-null int64
edu_exp_simi          175612 non-null float64
exp_desc_simi         175612 non-null float64
gitlang_simi          175612 non-null float64
idGit                 175612 non-null int64
idLink                175612 non-null object
label                 175612 non-null int64
linkedin_gitblog      175612 non-null float64
linkedin_gitweb       175612 non-null float64
linkweb_gitblog       175612 non-null float64
linkweb_github        175612 non-null float64
linkweb_gitweb        175612 non-null float64
location_fuzz_sort    175612 non-null int64
login_fuzz            175612 non-null int64
login_jw              175612 non-null float64
name_dmetaphone       175612 non-null float64
name_fuzz             175612 non-null int64
name_jw               175612 non-null float64
name_leven            175612 non-null int64
org_company           175612 non-null int64
org_school            175612 non-null int64
pro_pub_desc_simi     175612 non-null float64
pro_pub_title_simi    175612 non-null float64
school_company        175612 non-null int64
skill_simi            175612 non-null float64
summary_simi          175612 non-null float64
is_train              175612 non-null bool
prediction            175612 non-null int64
dtypes: bool(1), float64(16), int64(12), object(1)
memory usage: 45.4+ MB

In [76]:
test[test['idGit'].isin(test[y_score==1]['idGit'])]

,bio_simi,company_company,count,edu_exp_simi,exp_desc_simi,gitlang_simi,idGit,idLink,label,linkedin_gitblog,...,name_leven,org_company,org_school,pro_pub_desc_simi,pro_pub_title_simi,school_company,skill_simi,summary_simi,is_train,prediction
1,-1.000000,0,109,-1.000000,-1.000000,0.000000,100138,g3326641,0,0.666667,...,10,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100006,-1.000000,0,1,-1.000000,0.097342,0.144920,98012,g831365,1,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.140464,-1.000000,False,1
100160,-1.000000,17,3,-1.000000,0.072316,0.054422,106687,g841179,1,0.558824,...,0,0,0,0.014560,-1.000000,8,0.032381,-1.000000,False,1
100161,-1.000000,0,3,-1.000000,0.000000,0.058911,106687,g3397839,0,0.670411,...,1,0,0,0.000000,-1.000000,0,0.028862,-1.000000,False,0
100164,-1.000000,0,4,-1.000000,-1.000000,0.055395,107101,g3399653,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.030487,-1.000000,False,0
100165,-1.000000,0,4,-1.000000,-1.000000,0.118721,107101,g1228502,1,0.447368,...,0,0,0,-1.000000,-1.000000,0,0.038378,-1.000000,False,1
100166,-1.000000,0,4,-1.000000,-1.000000,-1.000000,107101,g3399660,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100172,-1.000000,44,1,-1.000000,-1.000000,0.163370,110020,g959391,1,0.670411,...,0,0,0,-1.000000,-1.000000,32,0.143190,-1.000000,False,1
100179,-1.000000,0,1,-1.000000,0.018070,0.039062,111119,g477640,0,0.685714,...,5,0,0,0.000000,-1.000000,0,0.025009,-1.000000,False,1
100181,-1.000000,0,4,-1.000000,0.035679,0.017850,111466,g4933738,0,0.740000,...,0,0,0,0.008599,-1.000000,0,0.028425,-1.000000,False,0
100182,-1.000000,0,4,-1.000000,0.054563,0.322840,111466,g599841,1,0.670411,...,0,0,0,0.003020,-1.000000,0,0.351094,-1.000000,False,1
100183,0.138852,40,4,0.000000,0.000000,0.005578,111466,g92285,0,0.670411,...,0,0,0,0.000000,-1.000000,22,0.003361,-1.000000,False,0
100395,-1.000000,100,2,-1.000000,0.055733,0.055404,112493,g65498,1,0.670411,...,0,0,0,-1.000000,-1.000000,28,0.041790,-1.000000,False,1
100408,-1.000000,25,1,-1.000000,-1.000000,0.031939,115832,g345318,1,0.848485,...,0,0,0,-1.000000,-1.000000,20,0.013443,-1.000000,False,1
100425,-1.000000,0,74,-1.000000,-1.000000,0.000000,120999,g3554073,0,0.670411,...,14,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100437,-1.000000,45,74,-1.000000,0.002695,0.000000,120999,g608677,0,0.500000,...,12,0,0,-1.000000,-1.000000,60,0.006316,-1.000000,False,0
100440,-1.000000,0,74,-1.000000,0.010050,0.000000,120999,g608707,0,0.670411,...,10,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100446,-1.000000,0,74,-1.000000,-1.000000,-1.000000,120999,g3554172,0,0.670411,...,8,0,0,-1.000000,-1.000000,0,-1.000000,-1.000000,False,0
100448,-1.000000,0,74,-1.000000,0.005074,0.000000,120999,g608706,0,0.670411,...,18,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100450,-1.000000,0,74,-1.000000,-1.000000,-1.000000,120999,g2920447,0,0.670411,...,10,0,0,-1.000000,-1.000000,0,-1.000000,-1.000000,False,0
100451,-1.000000,0,74,-1.000000,0.000000,-1.000000,120999,g3554200,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100452,-1.000000,100,74,-1.000000,0.131158,0.000000,120999,g608689,1,0.736842,...,0,0,0,-1.000000,-1.000000,35,0.000000,-1.000000,False,1
100453,-1.000000,13,74,-1.000000,-1.000000,-1.000000,120999,g608708,0,0.670411,...,0,0,0,-1.000000,-1.000000,18,0.000000,-1.000000,False,0
100456,-1.000000,0,74,-1.000000,0.000000,0.000000,120999,g3459353,0,0.670411,...,15,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100459,0.000000,0,74,0.000000,0.000000,0.000000,120999,g3554021,0,0.670411,...,1,0,0,-1.000000,-1.000000,0,0.031761,-1.000000,False,0
100461,-1.000000,31,74,-1.000000,-1.000000,-1.000000,120999,g1646770,0,0.670411,...,6,0,0,-1.000000,-1.000000,31,-1.000000,-1.000000,False,0
100462,-1.000000,0,74,-1.000000,-1.000000,0.000000,120999,g3554168,0,0.670411,...,16,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100465,0.000000,0,74,0.000000,0.000000,0.000000,120999,g3554179,0,0.670411,...,9,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100466,-1.000000,0,74,-1.000000,0.004538,0.000000,120999,g608703,0,0.526316,...,0,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
100468,0.000000,0,74,0.000000,-1.000000,0.000000,120999,g3554033,0,0.670411,...,7,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99342,-1.000000,0,12,-1.000000,-1.000000,-1.000000,68087,g5043185,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,-1.000000,-1.000000,False,0
99345,-1.000000,0,12,-1.000000,0.020918,0.000000,68087,g3141902,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
99348,-1.000000,0,12,-1.000000,0.000000,0.000000,68087,g3141891,0,0.670411,...,5,0,0,-1.000000,-1.000000,0,0.000000,-1.000000,False,0
9935,-1.000000,0,7,-1.000000,-1.000000,0.000000,109565,g3256709,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.015414,-1.000000,False,0
9938,-1.000000,100,7,-1.000000,-1.000000,0.134459,109565,g1370242,1,0.670411,...,0,0,0,-1.000000,-1.000000,30,0.076504,-1.000000,False,1
9942,0.000000,0,10,0.000000,0.011481,0.000000,110624,g5161010,0,0.670411,...,3,0,0,0.023125,0.000000,0,0.000000,-1.000000,False,0
99433,0.000000,43,4,0.000000,-1.000000,0.083529,69586,g357764,1,0.605263,...,0,0,0,-1.000000,-1.000000,23,0.118413,-1.000000,False,1
9944,0.000000,0,10,0.000000,0.005843,0.000000,110624,g5161025,0,0.670411,...,13,0,0,0.000873,0.000000,0,0.000000,-1.000000,False,0
99446,0.000000,9,1,0.000000,0.373408,-1.000000,71018,g363483,1,0.877551,...,0,0,0,-1.000000,-1.000000,13,-1.000000,-1.000000,False,1
99450,-1.000000,100,1,-1.000000,0.023946,0.068994,7174,g13076,1,0.700000,...,0,0,0,0.128569,-1.000000,100,0.017457,-1.000000,False,1
99451,0.117165,0,3,0.000000,-1.000000,0.101640,71792,g146712,1,0.578947,...,0,0,0,0.084022,0.000000,0,0.087234,-1.000000,False,1
99459,-1.000000,33,1,-1.000000,0.004847,0.120435,73665,g220171,1,0.670411,...,0,0,0,0.075620,-1.000000,27,0.101615,-1.000000,False,1
9946,-1.000000,38,10,-1.000000,-1.000000,-1.000000,110624,g606636,0,0.675676,...,3,0,0,-1.000000,-1.000000,42,-1.000000,-1.000000,False,0
99461,-1.000000,0,1,-1.000000,0.011400,0.048954,75106,g132510,1,0.670411,...,3,0,0,0.053123,-1.000000,0,0.017190,-1.000000,False,1
9947,0.201434,44,10,0.000000,0.169992,0.005336,110624,g606634,1,0.567568,...,0,0,0,0.098792,0.022148,34,0.043293,0.072759,False,1
99474,-1.000000,0,1,-1.000000,0.022279,0.104596,75497,g441597,1,0.670411,...,0,0,0,-1.000000,0.128172,0,0.125178,-1.000000,False,1
99477,-1.000000,0,1,-1.000000,0.002465,0.049920,75844,g3619468,0,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.007468,-1.000000,False,1
99482,-1.000000,60,1,-1.000000,0.039582,0.074709,7731,g15250,1,0.595238,...,0,0,0,-1.000000,-1.000000,13,0.010717,-1.000000,False,1
99485,-1.000000,100,1,-1.000000,0.005452,0.060663,77992,g239485,1,0.877551,...,0,0,0,0.016468,-1.000000,40,0.011860,-1.000000,False,1
9949,-1.000000,0,10,-1.000000,-1.000000,-1.000000,110624,g606637,0,0.670411,...,3,0,0,-1.000000,0.000000,0,0.000000,-1.000000,False,0
99521,-1.000000,100,1,0.416053,-1.000000,0.143905,79461,g129891,1,0.595238,...,0,0,0,0.058785,-1.000000,0,0.065931,-1.000000,False,1
99525,-1.000000,100,2,-1.000000,0.205808,0.016942,80042,g438483,1,0.647059,...,0,0,0,0.156397,-1.000000,34,0.010671,-1.000000,False,1
99532,-1.000000,0,2,-1.000000,0.065719,0.144528,82458,g220789,1,0.670411,...,13,0,0,0.078784,-1.000000,0,0.096928,-1.000000,False,1
99534,-1.000000,0,1,-1.000000,0.047785,0.140035,82614,g187018,1,0.795918,...,0,0,0,0.108640,-1.000000,0,0.130436,-1.000000,False,1
99650,-1.000000,100,1,-1.000000,0.241832,0.072603,841,g3381,1,0.670411,...,0,0,0,-1.000000,-1.000000,24,0.099878,-1.000000,False,1
99651,-1.000000,0,1,-1.000000,0.000000,0.115756,84446,g178499,1,0.463415,...,0,0,0,-1.000000,0.000000,0,0.067670,-1.000000,False,1
99653,-1.000000,0,1,-1.000000,0.031202,0.104161,84585,g353123,1,0.670411,...,0,0,0,-1.000000,-1.000000,0,0.075888,-1.000000,False,1
99837,-1.000000,37,1,-1.000000,0.000000,-1.000000,86907,g145114,1,0.794872,...,0,0,0,-1.000000,-1.000000,30,0.000000,-1.000000,False,1
99843,-1.000000,38,1,-1.000000,0.020002,0.161670,87221,g74329,1,0.605263,...,0,0,0,-1.000000,-1.000000,30,0.171060,-1.000000,False,1
99918,-1.000000,0,1,-1.000000,0.148063,0.045236,94398,g1181639,1,0.670411,...,0,0,0,0.092556,0.000000,0,0.017590,-1.000000,False,1

In [54]:
result = pd.DataFrame(zip(y_test, y_score))

In [55]:
result.columns = ['label','prediction']

In [56]:
pd.crosstab(result['label'], result['prediction'], rownames=['Actual label'], colnames=['Predicted label'])

Predicted label       0      1
Actual label
0                149977   1888
1                  3007  20740

In [40]:
from sklearn.metrics import average_precision_score
average_precision = average_precision_score(y_test, y_score)

print('Average precision-recall score: {0:0.2f}'.format(average_precision))

Average precision-recall score: 0.82

In [33]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175612 entries, 1 to 99998
Data columns (total 30 columns):
bio_simi              175612 non-null float64
company_company       175612 non-null int64
count                 175612 non-null int64
edu_exp_simi          175612 non-null float64
exp_desc_simi         175612 non-null float64
gitlang_simi          175612 non-null float64
idGit                 175612 non-null int64
idLink                175612 non-null object
label                 175612 non-null int64
linkedin_gitblog      175612 non-null float64
linkedin_gitweb       175612 non-null float64
linkweb_gitblog       175612 non-null float64
linkweb_github        175612 non-null float64
linkweb_gitweb        175612 non-null float64
location_fuzz_sort    175612 non-null int64
login_fuzz            175612 non-null int64
login_jw              175612 non-null float64
name_dmetaphone       175612 non-null float64
name_fuzz             175612 non-null int64
name_jw               175612 non-null float64
name_leven            175612 non-null int64
org_company           175612 non-null int64
org_school            175612 non-null int64
pro_pub_desc_simi     175612 non-null float64
pro_pub_title_simi    175612 non-null float64
school_company        175612 non-null int64
skill_simi            175612 non-null float64
summary_simi          175612 non-null float64
is_train              175612 non-null bool
prediction            175612 non-null int64
dtypes: bool(1), float64(16), int64(12), object(1)
memory usage: 45.4+ MB

In [25]:
import pickle

In [73]:
# save the model to disk
filename = '/home/jia/Dropbox/Startup/code/Talentful/data/rfModel.sav'
pickle.dump(rfModel, open(filename, 'wb'))

In [82]:
loaded_model = pickle.load(open(filename, 'rb'))